<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Gerard">
<meta name="dcterms.date" content="2026-06-18">

<title>One-Way ANOVA – Stat 302: Intermediate Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-33269adcf1721b81efc5ea7fcfe7f0ee.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/quarto-axe/axe-check.js" type="module"></script>
<script id="quarto-axe-checker-options" type="text/plain">dHJ1ZQ==</script>
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0e01d36e12aedd38e6bb7bd9a7358603.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Stat 302: Intermediate Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#case-studies" id="toc-case-studies" class="nav-link" data-scroll-target="#case-studies">Case Studies</a>
  <ul class="collapse">
  <li><a href="#case-study-5.1.1-diet-restriction-and-longevity" id="toc-case-study-5.1.1-diet-restriction-and-longevity" class="nav-link" data-scroll-target="#case-study-5.1.1-diet-restriction-and-longevity">Case Study 5.1.1: Diet Restriction and Longevity</a></li>
  <li><a href="#case-study-5.1.2-the-spock-conspiracy-trial" id="toc-case-study-5.1.2-the-spock-conspiracy-trial" class="nav-link" data-scroll-target="#case-study-5.1.2-the-spock-conspiracy-trial">Case Study 5.1.2: The Spock Conspiracy Trial</a></li>
  </ul></li>
  <li><a href="#the-statistical-model" id="toc-the-statistical-model" class="nav-link" data-scroll-target="#the-statistical-model">The Statistical Model</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a>
  <ul class="collapse">
  <li><a href="#pairwise-hypotheses" id="toc-pairwise-hypotheses" class="nav-link" data-scroll-target="#pairwise-hypotheses">Pairwise Hypotheses</a></li>
  <li><a href="#omnibus-hypothesis-are-any-means-different" id="toc-omnibus-hypothesis-are-any-means-different" class="nav-link" data-scroll-target="#omnibus-hypothesis-are-any-means-different">Omnibus Hypothesis (“Are <em>any</em> means different?”)</a></li>
  <li><a href="#one-group-vs.-the-rest" id="toc-one-group-vs.-the-rest" class="nav-link" data-scroll-target="#one-group-vs.-the-rest">One Group vs.&nbsp;the Rest</a></li>
  </ul></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a>
  <ul class="collapse">
  <li><a href="#group-sample-means" id="toc-group-sample-means" class="nav-link" data-scroll-target="#group-sample-means">Group Sample Means</a></li>
  <li><a href="#pooled-variance" id="toc-pooled-variance" class="nav-link" data-scroll-target="#pooled-variance">Pooled Variance</a></li>
  </ul></li>
  <li><a href="#testing-pairwise-differences" id="toc-testing-pairwise-differences" class="nav-link" data-scroll-target="#testing-pairwise-differences">Testing Pairwise Differences</a></li>
  <li><a href="#the-anova-f-test" id="toc-the-anova-f-test" class="nav-link" data-scroll-target="#the-anova-f-test">The ANOVA <span class="math inline">\(F\)</span>-Test</a>
  <ul class="collapse">
  <li><a href="#full-and-reduced-models" id="toc-full-and-reduced-models" class="nav-link" data-scroll-target="#full-and-reduced-models">Full and Reduced Models</a></li>
  <li><a href="#sums-of-squared-residuals" id="toc-sums-of-squared-residuals" class="nav-link" data-scroll-target="#sums-of-squared-residuals">Sums of Squared Residuals</a></li>
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic">The <span class="math inline">\(F\)</span>-Statistic</a></li>
  <li><a href="#the-f-distribution" id="toc-the-f-distribution" class="nav-link" data-scroll-target="#the-f-distribution">The <span class="math inline">\(F\)</span>-Distribution</a></li>
  <li><a href="#p-value-for-the-spock-omnibus-test" id="toc-p-value-for-the-spock-omnibus-test" class="nav-link" data-scroll-target="#p-value-for-the-spock-omnibus-test"><span class="math inline">\(p\)</span>-Value for the Spock Omnibus Test</a></li>
  </ul></li>
  <li><a href="#a-hierarchy-of-models" id="toc-a-hierarchy-of-models" class="nav-link" data-scroll-target="#a-hierarchy-of-models">A Hierarchy of Models</a></li>
  <li><a href="#one-way-anova-in-r" id="toc-one-way-anova-in-r" class="nav-link" data-scroll-target="#one-way-anova-in-r">One-Way ANOVA in R</a>
  <ul class="collapse">
  <li><a href="#checking-the-grouping-variable" id="toc-checking-the-grouping-variable" class="nav-link" data-scroll-target="#checking-the-grouping-variable">Checking the Grouping Variable</a></li>
  <li><a href="#omnibus-f-test-with-aov-and-summary" id="toc-omnibus-f-test-with-aov-and-summary" class="nav-link" data-scroll-target="#omnibus-f-test-with-aov-and-summary">Omnibus <span class="math inline">\(F\)</span>-Test with <code>aov()</code> and <code>summary()</code></a></li>
  <li><a href="#pairwise-comparisons" id="toc-pairwise-comparisons" class="nav-link" data-scroll-target="#pairwise-comparisons">Pairwise Comparisons</a></li>
  <li><a href="#nested-model-comparisons-with-anova" id="toc-nested-model-comparisons-with-anova" class="nav-link" data-scroll-target="#nested-model-comparisons-with-anova">Nested Model Comparisons with <code>anova()</code></a></li>
  <li><a href="#full-sequential-anova-table" id="toc-full-sequential-anova-table" class="nav-link" data-scroll-target="#full-sequential-anova-table">Full Sequential ANOVA Table</a></li>
  </ul></li>
  <li><a href="#assumptions-and-diagnostics" id="toc-assumptions-and-diagnostics" class="nav-link" data-scroll-target="#assumptions-and-diagnostics">Assumptions and Diagnostics</a>
  <ul class="collapse">
  <li><a href="#residual-plots-in-r" id="toc-residual-plots-in-r" class="nav-link" data-scroll-target="#residual-plots-in-r">Residual Plots in R</a></li>
  <li><a href="#manual-ggplot2-residual-plots" id="toc-manual-ggplot2-residual-plots" class="nav-link" data-scroll-target="#manual-ggplot2-residual-plots">Manual <code>ggplot2</code> Residual Plots</a></li>
  <li><a href="#what-to-look-for" id="toc-what-to-look-for" class="nav-link" data-scroll-target="#what-to-look-for">What to Look For</a></li>
  </ul></li>
  <li><a href="#random-effects" id="toc-random-effects" class="nav-link" data-scroll-target="#random-effects">Random Effects</a>
  <ul class="collapse">
  <li><a href="#the-random-effects-model" id="toc-the-random-effects-model" class="nav-link" data-scroll-target="#the-random-effects-model">The Random-Effects Model</a></li>
  <li><a href="#why-use-this-model" id="toc-why-use-this-model" class="nav-link" data-scroll-target="#why-use-this-model">Why Use This Model?</a></li>
  <li><a href="#intraclass-correlation-icc" id="toc-intraclass-correlation-icc" class="nav-link" data-scroll-target="#intraclass-correlation-icc">Intraclass Correlation (ICC)</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">One-Way ANOVA</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Gerard </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="learning-objectives" class="level1">
<h1>Learning Objectives</h1>
<ul>
<li>Explain the one-way ANOVA model for observational studies and randomized experiments.</li>
<li>State and interpret the three types of hypotheses: pairwise, omnibus, and one-group-vs-rest.</li>
<li>Compute and interpret the pooled variance estimate <span class="math inline">\(s_p^2\)</span>.</li>
<li>Conduct pairwise <span class="math inline">\(t\)</span>-tests using the pooled variance.</li>
<li>Set up and interpret the ANOVA <span class="math inline">\(F\)</span>-test using the extra-sum-of-squares framework.</li>
<li>Read a nested ANOVA table produced by R.</li>
<li>Check ANOVA assumptions with residual plots.</li>
<li>Describe the random-effects model and the intraclass correlation.</li>
</ul>
<hr>
</section>
<section id="case-studies" class="level1">
<h1>Case Studies</h1>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>case0501 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://dcgerard.github.io/stat_302/data/case0501.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>case0502 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://dcgerard.github.io/stat_302/data/case0502.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Judge =</span> <span class="fu">factor</span>(Judge))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="case-study-5.1.1-diet-restriction-and-longevity" class="level2">
<h2 class="anchored" data-anchor-id="case-study-5.1.1-diet-restriction-and-longevity">Case Study 5.1.1: Diet Restriction and Longevity</h2>
<p>A series of studies found that restricting caloric intake can dramatically increase life expectancy in animals. In one randomized experiment, female mice were assigned at random to one of six diet groups:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 53%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Label</th>
<th style="text-align: left;">Diet</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>NP</strong></td>
<td style="text-align: left;">Unlimited nonpurified standard diet</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>N/N85</strong></td>
<td style="text-align: left;">Normal diet before and after weaning; controlled at 85 kcal/wk after (serves as the control)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>N/R50</strong></td>
<td style="text-align: left;">Normal before weaning; restricted to 50 kcal/wk after</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>R/R50</strong></td>
<td style="text-align: left;">Restricted to 50 kcal/wk both before and after weaning</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>N/R50 lopro</strong></td>
<td style="text-align: left;">Like N/R50, but dietary protein decreased with advancing age</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>N/R40</strong></td>
<td style="text-align: left;">Normal before weaning; severely restricted to 40 kcal/wk after</td>
</tr>
</tbody>
</table>
<p>The response is <strong>lifetime in months</strong>. We are interested in:</p>
<ol type="1">
<li>Are <em>any</em> of the diets different from each other in terms of longevity?</li>
<li>Which specific diets differ, and by how much?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(case0501, <span class="fu">aes</span>(<span class="at">x =</span> Diet, <span class="at">y =</span> Lifetime)) <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Lifetime (months)"</span>, <span class="at">x =</span> <span class="st">"Diet group"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/diet-eda-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>case0501 <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Diet) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n       =</span> <span class="fu">n</span>(),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">Mean    =</span> <span class="fu">mean</span>(Lifetime),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD      =</span> <span class="fu">sd</span>(Lifetime),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">Median  =</span> <span class="fu">median</span>(Lifetime)) <span class="sc">|&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Diet</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N/N85</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">32.7</td>
<td style="text-align: right;">5.1</td>
<td style="text-align: right;">33.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">N/R40</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">45.1</td>
<td style="text-align: right;">6.7</td>
<td style="text-align: right;">46.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">N/R50</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">42.3</td>
<td style="text-align: right;">7.8</td>
<td style="text-align: right;">43.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">NP</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">27.4</td>
<td style="text-align: right;">6.1</td>
<td style="text-align: right;">28.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R/R50</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">42.9</td>
<td style="text-align: right;">6.7</td>
<td style="text-align: right;">44.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">lopro</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">39.7</td>
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">41.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="case-study-5.1.2-the-spock-conspiracy-trial" class="level2">
<h2 class="anchored" data-anchor-id="case-study-5.1.2-the-spock-conspiracy-trial">Case Study 5.1.2: The Spock Conspiracy Trial</h2>
<p>In 1968, Dr.&nbsp;Benjamin Spock was tried in Boston on charges related to encouraging draft resistance during the Vietnam War. The defense argued that the Spock trial judge (referred to here as “Spock’s” judge) systematically underrepresented women on jury venires. They compared this judge’s venires with those of six other Boston-area district judges (labeled A–F).</p>
<p>This is an <strong>observational study</strong>: judge assignment to cases was not randomized.</p>
<p>The response is <code>Percent</code> — the percentage of women on each venire. We are interested in:</p>
<ol type="1">
<li>Is Spock’s judge’s mean percent-women lower than the other judges?</li>
<li>Are the other judges’ means all the same?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(case0502, <span class="fu">aes</span>(<span class="at">x =</span> Judge, <span class="at">y =</span> Percent)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Percent women on venire"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/spock-eda-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(case0502, <span class="fu">aes</span>(<span class="at">x =</span> Judge, <span class="at">y =</span> Percent)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">height =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"crossbar"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">"tomato"</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>, <span class="at">width =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Percent women on venire"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Red bars = group sample means"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/spock-dotplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="the-statistical-model" class="level1">
<h1>The Statistical Model</h1>
<p>In each case study we are comparing means across <span class="math inline">\(I\)</span> groups. We observe <span class="math inline">\(n_i\)</span> individuals in group <span class="math inline">\(i\)</span>, for a total of <span class="math inline">\(n = n_1 + n_2 + \cdots + n_I\)</span> observations.</p>
<p><strong>Notation:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Symbol</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\mu_i\)</span></td>
<td style="text-align: left;">True population mean for group <span class="math inline">\(i\)</span>, <span class="math inline">\(i = 1, \ldots, I\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(Y_{ij}\)</span></td>
<td style="text-align: left;">Observed value for the <span class="math inline">\(j\)</span>th individual in group <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\varepsilon_{ij}\)</span></td>
<td style="text-align: left;">Individual-specific noise for the <span class="math inline">\(j\)</span>th individual in group <span class="math inline">\(i\)</span>: mean 0, variance <span class="math inline">\(\sigma^2\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Model:</strong> <span class="math display">\[Y_{ij} = \mu_i + \varepsilon_{ij}\]</span></p>
<p>In words: each observed value equals the true group mean plus a random individual-level noise term. The noise captures everything we can’t explain — genetic variation between mice, measurement error, day-to-day fluctuation in a judge’s venire composition, etc.</p>
<p>The key restriction is <strong>equal variance</strong>: <span class="math inline">\(\sigma^2\)</span> is assumed the same for every group and every individual. A mouse in the N/R40 diet group has the same background noise variance as a mouse in the NP group; they just have different expected lifetimes. This is the <span class="math inline">\(I\)</span>-group generalization of the pooled two-sample <span class="math inline">\(t\)</span>-test from Chapter 2.</p>
<p><strong>Spock trial interpretation:</strong></p>
<ul>
<li><span class="math inline">\(\mu_1\)</span> = true mean percent-women for Spock’s judge across all possible venires</li>
<li><span class="math inline">\(\mu_i\)</span> = true mean percent-women for judge <span class="math inline">\(i\)</span>, <span class="math inline">\(i = 2, \ldots, 7\)</span> (judges A–F)</li>
<li><span class="math inline">\(Y_{ij}\)</span> = observed percent women on venire <span class="math inline">\(j\)</span> of judge <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\varepsilon_{ij}\)</span> = random variation in how that particular venire was drawn</li>
</ul>
<p><strong>Observational vs.&nbsp;randomized:</strong> The model equation <span class="math inline">\(Y_{ij} = \mu_i + \varepsilon_{ij}\)</span> looks the same in both settings, but the randomized experiment has a useful additional interpretation. In the diet study, the same individual mouse could in principle have been assigned to any diet. If we call the response under diet 1 (N/N85, the control) <span class="math inline">\(Y^* = \mu_1 + \varepsilon_j\)</span>, then the same mouse under diet <span class="math inline">\(i\)</span> would have response:</p>
<p><span class="math display">\[Y_j^{(i)} = \mu_i + \varepsilon_j
             = (\mu_i - \mu_1) + \mu_1 + \varepsilon_j
             = \delta_i + Y^*\]</span></p>
<p>where <span class="math inline">\(\delta_i = \mu_i - \mu_1\)</span> is the <strong>treatment effect</strong> of diet <span class="math inline">\(i\)</span> relative to the control. Because diets were randomly assigned, <span class="math inline">\(\delta_i\)</span> has a genuine causal interpretation: it is how much longer (or shorter) a mouse would live if assigned to diet <span class="math inline">\(i\)</span> instead of the control.</p>
<p>In an observational study we cannot make this argument — the “same individual under a different group” is a counterfactual we cannot observe, and confounding may explain any observed difference.</p>
<p>The difference is in the conclusions:</p>
<ul>
<li><strong>Observational study</strong> (Spock trial): use associational language (“is associated with”, “differs between”).</li>
<li><strong>Randomized experiment</strong> (diet study): use causal language (“causes”, “results in”, “affects”).</li>
</ul>
<hr>
</section>
<section id="hypotheses" class="level1">
<h1>Hypotheses</h1>
<p>With <span class="math inline">\(I\)</span> groups there are many possible hypotheses.</p>
<section id="pairwise-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="pairwise-hypotheses">Pairwise Hypotheses</h2>
<p>Test whether any specific pair of means differs: <span class="math display">\[H_0: \mu_2 = \mu_5, \qquad H_A: \mu_2 \neq \mu_5\]</span></p>
<p>With <span class="math inline">\(I = 7\)</span> groups there are <span class="math inline">\(\binom{7}{2} = 21\)</span> possible pairwise tests.</p>
</section>
<section id="omnibus-hypothesis-are-any-means-different" class="level2">
<h2 class="anchored" data-anchor-id="omnibus-hypothesis-are-any-means-different">Omnibus Hypothesis (“Are <em>any</em> means different?”)</h2>
<p><span class="math display">\[H_0: \mu_1 = \mu_2 = \mu_3 = \mu_4 = \mu_5 = \mu_6 = \mu_7\]</span> <span class="math display">\[H_A: \text{at least one } \mu_i \neq \mu_j\]</span></p>
</section>
<section id="one-group-vs.-the-rest" class="level2">
<h2 class="anchored" data-anchor-id="one-group-vs.-the-rest">One Group vs.&nbsp;the Rest</h2>
<p><span class="math display">\[H_0: \mu_1 = \tfrac{1}{6}(\mu_2 + \mu_3 + \mu_4 + \mu_5 + \mu_6 + \mu_7)\]</span> <span class="math display">\[H_A: \mu_1 \neq \tfrac{1}{6}(\mu_2 + \mu_3 + \mu_4 + \mu_5 + \mu_6 + \mu_7)\]</span></p>
<p>This asks: <em>Is Spock’s judge’s mean different from the average of the other judges?</em></p>
<hr>
</section>
</section>
<section id="estimation" class="level1">
<h1>Estimation</h1>
<section id="group-sample-means" class="level2">
<h2 class="anchored" data-anchor-id="group-sample-means">Group Sample Means</h2>
<p>Estimate <span class="math inline">\(\mu_i\)</span> with the group sample mean: <span class="math display">\[\bar{Y}_{i\bullet} = \frac{1}{n_i}\sum_{j=1}^{n_i} Y_{ij}\]</span></p>
</section>
<section id="pooled-variance" class="level2">
<h2 class="anchored" data-anchor-id="pooled-variance">Pooled Variance</h2>
<p>Each group has its own sample standard deviation <span class="math inline">\(s_i\)</span>, measuring the spread of observations <em>within</em> that group. Because we assume the same true variance <span class="math inline">\(\sigma^2\)</span> for every group, we can combine these within-group estimates into one more accurate estimate. We weight each group by the amount of information it contributes — groups with more observations get more weight:</p>
<p><span class="math display">\[s_p^2 = \frac{(n_1-1)s_1^2 + (n_2-1)s_2^2 + \cdots + (n_I-1)s_I^2}
               {(n_1-1) + (n_2-1) + \cdots + (n_I-1)}\]</span></p>
<p>In words: each term <span class="math inline">\((n_i-1)s_i^2\)</span> in the numerator is the sum of squared deviations from group <span class="math inline">\(i\)</span>’s mean. Adding these across all groups gives the total within-group variation. Dividing by the total degrees of freedom gives the average within-group variance.</p>
<p>The denominator is <span class="math inline">\(\nu = n - I\)</span> (the total degrees of freedom available for estimating variance within groups — we lose one degree of freedom per group because we estimated each group’s mean).</p>
<p>Two observations: - This is a weighted average of the within-group variance estimates, weighted by their degrees of freedom. - When <span class="math inline">\(I = 2\)</span> this reduces exactly to the pooled variance from Chapter 2.</p>
<hr>
</section>
</section>
<section id="testing-pairwise-differences" class="level1">
<h1>Testing Pairwise Differences</h1>
<p>To test <span class="math inline">\(H_0: \mu_i = \mu_j\)</span> vs <span class="math inline">\(H_A: \mu_i \neq \mu_j\)</span>, we build a <span class="math inline">\(t\)</span>-statistic in three steps.</p>
<p><strong>Step 1 — Distribution of the difference under <span class="math inline">\(H_0\)</span>.</strong> Each group mean is approximately normal: <span class="math inline">\(\bar{Y}_{i\bullet} \sim N(\mu_i,\; \sigma^2/n_i)\)</span>. Under <span class="math inline">\(H_0\)</span> (<span class="math inline">\(\mu_i = \mu_j\)</span>), the two means are independent, so their difference is: <span class="math display">\[\bar{Y}_{i\bullet} - \bar{Y}_{j\bullet}
  \;\sim\; N\!\left(0,\; \sigma^2\!\left(\tfrac{1}{n_i} + \tfrac{1}{n_j}\right)\right)\]</span></p>
<p><strong>Step 2 — Standardize.</strong> Dividing by the true standard deviation gives a standard normal: <span class="math display">\[\frac{\bar{Y}_{i\bullet} - \bar{Y}_{j\bullet}}
      {\sigma\sqrt{1/n_i + 1/n_j}} \;\sim\; N(0,1)\]</span></p>
<p><strong>Step 3 — Estimate <span class="math inline">\(\sigma\)</span>.</strong> We don’t know <span class="math inline">\(\sigma\)</span>, so we substitute the pooled estimate <span class="math inline">\(s_p\)</span>. Replacing a known standard deviation with an estimate inflates uncertainty, and the result follows a <span class="math inline">\(t\)</span> distribution:</p>
<p><span class="math display">\[t^* = \frac{\bar{Y}_{i\bullet} - \bar{Y}_{j\bullet}}{s_p\sqrt{1/n_i + 1/n_j}}
       \;\sim\; t_\nu
       \quad \text{under } H_0\]</span></p>
<p>where <span class="math inline">\(\nu = n - I\)</span>.</p>
<p><strong>Why <span class="math inline">\(\nu = n - I\)</span>?</strong> Because <span class="math inline">\(s_p^2\)</span> uses <em>all <span class="math inline">\(n\)</span> observations across all <span class="math inline">\(I\)</span> groups</em> to estimate <span class="math inline">\(\sigma^2\)</span> — not just the <span class="math inline">\(n_i + n_j\)</span> observations in the two groups being compared. Using more data gives a better estimate, which in turn gives larger degrees of freedom (<span class="math inline">\(n - I\)</span> instead of <span class="math inline">\(n_i + n_j - 2\)</span>), making the <span class="math inline">\(t\)</span> distribution closer to a standard normal and the test more powerful.</p>
<p>The advantage over running separate two-sample <span class="math inline">\(t\)</span>-tests is that <strong>we use all the data to estimate <span class="math inline">\(\sigma^2\)</span></strong>, giving more degrees of freedom and a more accurate variance estimate.</p>
<p>A 95% confidence interval for <span class="math inline">\(\mu_i - \mu_j\)</span> is:</p>
<p><span class="math display">\[\bar{Y}_{i\bullet} - \bar{Y}_{j\bullet}
  \;\pm\; t_{\nu}(0.975) \cdot s_p\sqrt{1/n_i + 1/n_j}\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Multiple Comparisons
</div>
</div>
<div class="callout-body-container callout-body">
<p>Running 21 pairwise tests at <span class="math inline">\(\alpha = 0.05\)</span> inflates the overall Type I error rate well above 5%. Chapter 6 covers methods that control for multiple comparisons. For now, we treat each pairwise test independently and note the concern.</p>
</div>
</div>
<hr>
</section>
<section id="the-anova-f-test" class="level1">
<h1>The ANOVA <span class="math inline">\(F\)</span>-Test</h1>
<p>For the omnibus hypothesis (<span class="math inline">\(H_0\)</span>: all means equal vs <span class="math inline">\(H_A\)</span>: at least two differ), a single summary statistic is needed. The ANOVA <span class="math inline">\(F\)</span>-test compares two <strong>nested models</strong> by asking: <em>how much does model fit improve when we allow separate group means?</em></p>
<section id="full-and-reduced-models" class="level2">
<h2 class="anchored" data-anchor-id="full-and-reduced-models">Full and Reduced Models</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Reduced model (<span class="math inline">\(H_0\)</span>)</th>
<th style="text-align: left;">Full model (<span class="math inline">\(H_A\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Means</strong></td>
<td style="text-align: left;"><span class="math inline">\(\mu_1 = \mu_2 = \cdots = \mu_I = \mu\)</span> (one shared mean)</td>
<td style="text-align: left;"><span class="math inline">\(\mu_1, \mu_2, \ldots, \mu_I\)</span> (separate means)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Estimates</strong></td>
<td style="text-align: left;"><span class="math inline">\(\hat{\mu} = \bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\hat{\mu}_i = \bar{Y}_{i\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong># parameters</strong></td>
<td style="text-align: left;">1</td>
<td style="text-align: left;"><span class="math inline">\(I\)</span></td>
</tr>
</tbody>
</table>
<p>For the Spock data (<span class="math inline">\(I = 7\)</span> judges), here is what each model predicts for each group:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: left;">Judge</th>
<th style="text-align: center;">Full model prediction</th>
<th style="text-align: center;">Reduced model prediction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">Spock’s</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{1\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">Judge A</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{2\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">Judge B</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{3\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">Judge C</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{4\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;">Judge D</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{5\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;">Judge E</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{6\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;">Judge F</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{7\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
</tr>
</tbody>
</table>
<p>In the <strong>full model</strong>, each group gets its own sample mean as a prediction. Spock’s judge’s venires are predicted by Spock’s judge’s average; Judge A’s venires are predicted by Judge A’s average; and so on. There are 7 free parameters — one per judge.</p>
<p>In the <strong>reduced model</strong>, every observation — regardless of judge — is predicted by the same grand average <span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span> (the mean over all 46 venires). This is the model that says <span class="math inline">\(H_0\)</span> is true: if all judges have the same expected percent-women, then the best single prediction for any venire is just the overall average.</p>
<p><strong>What is a residual?</strong> A residual is simply the distance between an observed value and the model’s prediction for it:</p>
<ul>
<li>Full model residual: <span class="math inline">\(Y_{ij} - \bar{Y}_{i\bullet}\)</span> — how far observation <span class="math inline">\((i,j)\)</span> is from <em>its group’s mean</em></li>
<li>Reduced model residual: <span class="math inline">\(Y_{ij} - \bar{Y}_{\bullet\bullet}\)</span> — how far observation <span class="math inline">\((i,j)\)</span> is from <em>the grand mean</em></li>
</ul>
<p>Intuitively, if the groups really have different means, the full model residuals will be small (each observation is close to its own group mean), while the reduced model residuals will be large (observations from Spock’s group, for example, are far from the overall grand mean).</p>
</section>
<section id="sums-of-squared-residuals" class="level2">
<h2 class="anchored" data-anchor-id="sums-of-squared-residuals">Sums of Squared Residuals</h2>
<p>The <strong>residual sum of squares</strong> (RSS) for each model is:</p>
<p><span class="math display">\[RSS_{full} = \sum_i \sum_j (Y_{ij} - \bar{Y}_{i\bullet})^2,
\quad df_{full} = n - I\]</span></p>
<p><span class="math display">\[RSS_{reduced} = \sum_i \sum_j (Y_{ij} - \bar{Y}_{\bullet\bullet})^2,
\quad df_{reduced} = n - 1\]</span></p>
<p>Each RSS adds up all the squared residuals across every observation. Think of it as a scoreboard for how badly the model is fitting: a small RSS means predictions are close to the data; a large RSS means they are far away. Both RSS values involve squaring (so positive and negative residuals don’t cancel) and summing (so we get a single overall measure).</p>
<p>The <strong>extra sum of squares</strong> (ESS) measures how much the fit improves when we go from the reduced model to the full model:</p>
<p><span class="math display">\[ESS = RSS_{reduced} - RSS_{full}, \quad df_{extra} = I - 1\]</span></p>
<p><strong>Why is <span class="math inline">\(RSS_{reduced} \geq RSS_{full}\)</span> always?</strong> The full model has the reduced model as a special case: if all the <span class="math inline">\(\mu_i\)</span> happen to be equal, the full model’s separate group means would all estimate the same value as the grand mean, and the two models would give identical fits. In general, the full model has more flexibility, so it can <em>never</em> fit worse than the reduced model — it can always do at least as well. Therefore <span class="math inline">\(ESS \geq 0\)</span> always.</p>
<p><strong>What does ESS tell us?</strong> If <span class="math inline">\(H_0\)</span> is true (all means really are equal), fitting separate group means should not improve the fit by very much — the data don’t contain strong evidence for distinct groups. In that case, ESS will be positive but small. If the means truly differ (the data come from groups with different means), the full model will fit much better, and ESS will be large. The <span class="math inline">\(F\)</span>-test formalizes what “small” and “large” mean.</p>
<p>The plots below illustrate this for the Spock data. Red bars/lines show the model’s fitted means; larger gaps between points and those lines = larger residuals.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/null-vs-full-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The squared residuals are much smaller under the full model, confirming that group means differ substantially.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/sq-resid-boxplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-f-statistic" class="level2">
<h2 class="anchored" data-anchor-id="the-f-statistic">The <span class="math inline">\(F\)</span>-Statistic</h2>
<p>If <span class="math inline">\(H_0\)</span> is true, both <span class="math inline">\(ESS/df_{extra}\)</span> and <span class="math inline">\(RSS_{full}/df_{full} = s_p^2\)</span> estimate the same <span class="math inline">\(\sigma^2\)</span>, so their ratio should be near 1. If <span class="math inline">\(H_A\)</span> is true, the means differ and <span class="math inline">\(ESS\)</span> will be inflated, pushing the ratio above 1.</p>
<p><span class="math display">\[F = \frac{ESS / df_{extra}}{s_p^2}
    = \frac{ESS / (I-1)}{RSS_{full} / (n-I)}\]</span></p>
<p>Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(F \sim F_{I-1,\; n-I}\)</span>. The <span class="math inline">\(p\)</span>-value uses only the upper tail (large <span class="math inline">\(F\)</span> is evidence against <span class="math inline">\(H_0\)</span>).</p>
</section>
<section id="the-f-distribution" class="level2">
<h2 class="anchored" data-anchor-id="the-f-distribution">The <span class="math inline">\(F\)</span>-Distribution</h2>
<p>The <span class="math inline">\(F\)</span> distribution is parameterized by two degrees of freedom: numerator (<span class="math inline">\(df_1\)</span>) and denominator (<span class="math inline">\(df_2\)</span>). Below are a few shapes:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/f-dist-shapes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="p-value-for-the-spock-omnibus-test" class="level2">
<h2 class="anchored" data-anchor-id="p-value-for-the-spock-omnibus-test"><span class="math inline">\(p\)</span>-Value for the Spock Omnibus Test</h2>
<p>The Spock data has <span class="math inline">\(I = 7\)</span> judges and <span class="math inline">\(n = 46\)</span> venires, so <span class="math inline">\(df_{extra} = 6\)</span> and <span class="math inline">\(df_{full} = 39\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>n     <span class="ot">&lt;-</span> <span class="fu">nrow</span>(case0502)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>I     <span class="ot">&lt;-</span> <span class="fu">n_distinct</span>(case0502<span class="sc">$</span>Judge)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df_extra <span class="ot">&lt;-</span> I <span class="sc">-</span> <span class="dv">1</span>          <span class="co"># 6</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>df_full  <span class="ot">&lt;-</span> n <span class="sc">-</span> I          <span class="co"># 39</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ess      <span class="ot">&lt;-</span> rss_null <span class="sc">-</span> rss_full</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>sp2      <span class="ot">&lt;-</span> rss_full <span class="sc">/</span> df_full</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>fstat    <span class="ot">&lt;-</span> (ess <span class="sc">/</span> df_extra) <span class="sc">/</span> sp2</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">ESS =</span> ess, <span class="at">RSS_full =</span> rss_full, <span class="at">sp2 =</span> sp2, <span class="at">F =</span> fstat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ESS RSS_full      sp2        F 
1927.081 1864.445   47.806    6.718 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(fstat, <span class="at">df1 =</span> df_extra, <span class="at">df2 =</span> df_full, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.096e-05</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/spock-f-plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="a-hierarchy-of-models" class="level1">
<h1>A Hierarchy of Models</h1>
<p>In more complex questions we compare <strong>three</strong> or more nested models. Each model is a special case of the next:</p>
<ul>
<li><strong>Null</strong>: all means equal <span class="math inline">\((\mu)\)</span></li>
<li><strong>Intermediate</strong>: Spock’s judge differs from a common mean for the rest <span class="math inline">\((\mu_\text{Spock}, \mu_\text{others})\)</span></li>
<li><strong>Full</strong>: all seven means free <span class="math inline">\((\mu_1, \mu_2, \ldots, \mu_7)\)</span></li>
</ul>
<p>Here is what each model predicts for each judge in the Spock data.</p>
<p><strong>Null vs.&nbsp;Intermediate</strong> — Is Spock’s judge different from the rest?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: left;">Judge</th>
<th style="text-align: center;">Null (reduced)</th>
<th style="text-align: center;">Intermediate (full)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">Spock’s</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{1\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">Judge A</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">Judge B</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">Judge C</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;">Judge D</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;">Judge E</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;">Judge F</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
</tr>
</tbody>
</table>
<p>Here <span class="math inline">\(\bar{Y}_{\bullet\bullet}\)</span> is the grand mean of all 46 venires, and <span class="math inline">\(\bar{Y}_{0}\)</span> is the average percent-women across all venires belonging to judges A–F (groups 2 through 7). The intermediate model has 2 parameters: one for Spock’s judge (<span class="math inline">\(\bar{Y}_{1\bullet}\)</span>) and one pooled mean for the remaining six judges (<span class="math inline">\(\bar{Y}_{0}\)</span>).</p>
<p><strong>Intermediate vs.&nbsp;Full</strong> — Do judges A–F differ among themselves?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: left;">Judge</th>
<th style="text-align: center;">Intermediate (reduced)</th>
<th style="text-align: center;">Full</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">Spock’s</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{1\bullet}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{1\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">Judge A</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{2\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">Judge B</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{3\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">Judge C</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{4\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;">Judge D</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{5\bullet}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;">Judge E</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{6\bullet}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;">Judge F</td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{0}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\bar{Y}_{7\bullet}\)</span></td>
</tr>
</tbody>
</table>
<p>This test asks: after accounting for Spock’s judge, do the remaining six judges’ venires show any systematic differences from each other?</p>
<p>Notice that we always fit <em>both</em> models using <em>all</em> the data — we never discard Spock’s judge’s observations even when comparing only judges A–F. This matters for the variance estimate: instead of testing on a subset of 39 venires (judges A–F only, <span class="math inline">\(df = 32\)</span>), we keep all 46 venires and use <span class="math inline">\(s_p^2\)</span> from the full model (<span class="math inline">\(df = 39\)</span>). More degrees of freedom means a better variance estimate and a more powerful test.</p>
<p>Each <span class="math inline">\(F\)</span>-test compares adjacent models. Crucially, <strong>all F-tests use the variance estimate <span class="math inline">\(s_p^2 = RSS_{full}/df_{full}\)</span> from the most general (full) model</strong>, regardless of which pair is being compared.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ch5_fig/model_hierarchy.svg" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Hierarchy of models for the Spock trial. Arrows show <span class="math inline">\(F\)</span>-tests between adjacent models. RSS = residual sum of squares; df = degrees of freedom.</figcaption>
</figure>
</div>
<p>The full sequential ANOVA table for the Spock data is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: center;"><span class="math inline">\(df_{RSS}\)</span></th>
<th style="text-align: right;">RSS</th>
<th style="text-align: center;"><span class="math inline">\(df_{extra}\)</span></th>
<th style="text-align: right;">ESS</th>
<th style="text-align: right;"><span class="math inline">\(F\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">All same</td>
<td style="text-align: center;">45</td>
<td style="text-align: right;">3792</td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Spock’s differs</td>
<td style="text-align: center;">44</td>
<td style="text-align: right;">2191</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">1601</td>
<td style="text-align: right;">33.48</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">All different</td>
<td style="text-align: center;">39</td>
<td style="text-align: right;">1864</td>
<td style="text-align: center;">5</td>
<td style="text-align: right;">326</td>
<td style="text-align: right;">1.37</td>
<td style="text-align: right;">0.26</td>
</tr>
</tbody>
</table>
<p><strong>Conclusions:</strong></p>
<ul>
<li>Strong evidence that Spock’s judge has a different (lower) mean than the other judges (<span class="math inline">\(F_{1,39} = 33.48\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>).</li>
<li>No evidence that the six non-Spock judges differ among themselves (<span class="math inline">\(F_{5,39} = 1.37\)</span>, <span class="math inline">\(p = 0.26\)</span>).</li>
</ul>
<p>Note: the <span class="math inline">\(F\)</span>-statistic in the table uses <span class="math inline">\(s_p^2 = 1864/39 \approx 47.8\)</span> (from the <strong>full</strong> model) as the denominator throughout.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><span class="math inline">\(s_p^2\)</span> is not the same as the overall sample variance
</div>
</div>
<div class="callout-body-container callout-body">
<p>The pooled variance <span class="math inline">\(s_p^2 = RSS_{full}/39 = 1864/39 \approx 48\)</span> measures how much observations vary <em>within</em> groups — after accounting for differences in group means. It is what ANOVA uses to estimate <span class="math inline">\(\sigma^2\)</span>.</p>
<p>If you ignored the groups entirely and computed a single sample variance for all 46 venires, you would get <span class="math inline">\(s^2 = RSS_{reduced}/45 = 3792/45 \approx 84\)</span>. This is larger because it lumps together within-group and between-group variation — the judges have different means, and that extra spread inflates <span class="math inline">\(s^2\)</span>. Using <span class="math inline">\(s_p^2\)</span> removes the between-group contribution and focuses on the within-group noise, giving a better estimate of <span class="math inline">\(\sigma^2\)</span>.</p>
</div>
</div>
<hr>
</section>
<section id="one-way-anova-in-r" class="level1">
<h1>One-Way ANOVA in R</h1>
<section id="checking-the-grouping-variable" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-grouping-variable">Checking the Grouping Variable</h2>
<p>Before fitting, confirm the grouping variable is a <code>factor</code> or <code>character</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(case0502<span class="sc">$</span>Judge)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
</div>
<p>If it were numeric, <code>aov()</code> would treat it as a continuous predictor, not a grouping variable. Use <code>as.factor()</code> or <code>mutate(Judge = factor(Judge))</code> to fix this.</p>
</section>
<section id="omnibus-f-test-with-aov-and-summary" class="level2">
<h2 class="anchored" data-anchor-id="omnibus-f-test-with-aov-and-summary">Omnibus <span class="math inline">\(F\)</span>-Test with <code>aov()</code> and <code>summary()</code></h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>aout_full <span class="ot">&lt;-</span> <span class="fu">aov</span>(Percent <span class="sc">~</span> Judge, <span class="at">data =</span> case0502)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aout_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)
Judge        6   1927     321    6.72 6.1e-05
Residuals   39   1864      48                </code></pre>
</div>
</div>
<p>The table has two rows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Row</th>
<th style="text-align: left;"><span class="math inline">\(df\)</span></th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;"><span class="math inline">\(F\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p\)</span>-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Judge</code></td>
<td style="text-align: left;"><span class="math inline">\(df_{extra} = I - 1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(ESS\)</span></td>
<td style="text-align: right;"><span class="math inline">\(ESS / df_{extra}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(F\)</span>-stat</td>
<td style="text-align: right;"><span class="math inline">\(p\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Residuals</code></td>
<td style="text-align: left;"><span class="math inline">\(df_{full} = n - I\)</span></td>
<td style="text-align: right;"><span class="math inline">\(RSS_{full}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(RSS_{full}/df_{full} = s_p^2\)</span></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</section>
<section id="pairwise-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="pairwise-comparisons">Pairwise Comparisons</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ptout <span class="ot">&lt;-</span> <span class="fu">pairwise.t.test</span>(<span class="at">x =</span> case0502<span class="sc">$</span>Percent,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">g =</span> case0502<span class="sc">$</span>Judge,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">p.adjust.method =</span> <span class="st">"none"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>ptout</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  case0502$Percent and case0502$Judge 

        A     B     C     D     E     F    
B       0.905 -     -     -     -     -    
C       0.201 0.223 -     -     -     -    
D       0.226 0.248 0.700 -     -     -    
E       0.095 0.104 0.562 0.995 -     -    
F       0.065 0.069 0.485 0.971 0.964 -    
Spock's 1e-05 6e-06 7e-05 0.028 0.002 6e-04

P value adjustment method: none </code></pre>
</div>
</div>
<p>Each cell is the raw (unadjusted) <span class="math inline">\(p\)</span>-value for that pair. Note that <code>pairwise.t.test()</code> uses <span class="math inline">\(s_p^2\)</span> from <strong>all</strong> groups to form the <span class="math inline">\(t\)</span>-statistic, even when comparing just two groups.</p>
</section>
<section id="nested-model-comparisons-with-anova" class="level2">
<h2 class="anchored" data-anchor-id="nested-model-comparisons-with-anova">Nested Model Comparisons with <code>anova()</code></h2>
<p>To test the intermediate hypothesis (Spock’s differs; others pooled):</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>case0502 <span class="ot">&lt;-</span> case0502 <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">isSpock =</span> Judge <span class="sc">==</span> <span class="st">"Spock's"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>aout_intermediate <span class="ot">&lt;-</span> <span class="fu">aov</span>(Percent <span class="sc">~</span> isSpock, <span class="at">data =</span> case0502)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>aout_null         <span class="ot">&lt;-</span> <span class="fu">aov</span>(Percent <span class="sc">~</span> <span class="dv">1</span>,       <span class="at">data =</span> case0502)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(aout_intermediate, aout_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Percent ~ isSpock
Model 2: Percent ~ Judge
  Res.Df  RSS Df Sum of Sq    F Pr(&gt;F)
1     44 2191                         
2     39 1864  5       326 1.37   0.26</code></pre>
</div>
</div>
<p>The rows are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 23%">
<col style="width: 9%">
<col style="width: 27%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Row</th>
<th style="text-align: center;"><span class="math inline">\(df_{RSS}\)</span></th>
<th style="text-align: right;">RSS</th>
<th style="text-align: center;"><span class="math inline">\(df_{extra}\)</span></th>
<th style="text-align: right;">ESS</th>
<th style="text-align: right;"><span class="math inline">\(F\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Model 1 (reduced)</td>
<td style="text-align: center;"><span class="math inline">\(df_{reduced}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(RSS_{reduced}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Model 2 (full)</td>
<td style="text-align: center;"><span class="math inline">\(df_{full}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(RSS_{full}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(df_{extra}\)</span></td>
<td style="text-align: right;">ESS</td>
<td style="text-align: right;"><span class="math inline">\(F\)</span>-stat</td>
<td style="text-align: right;"><span class="math inline">\(p\)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="full-sequential-anova-table" class="level2">
<h2 class="anchored" data-anchor-id="full-sequential-anova-table">Full Sequential ANOVA Table</h2>
<p>Compare all three models at once:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(aout_null, aout_intermediate, aout_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Percent ~ 1
Model 2: Percent ~ isSpock
Model 3: Percent ~ Judge
  Res.Df  RSS Df Sum of Sq     F Pr(&gt;F)
1     45 3792                          
2     44 2191  1      1601 33.48  1e-06
3     39 1864  5       326  1.37   0.26</code></pre>
</div>
</div>
<p>This produces the sequential table shown in the hierarchy section above. Row 2 tests Null vs Intermediate; Row 3 tests Intermediate vs Full.</p>
<p>Note: the <span class="math inline">\(F\)</span>-statistics shown here use <span class="math inline">\(s_p^2\)</span> from the <strong>full</strong> model (<code>aout_full</code>) as the denominator.</p>
<hr>
</section>
</section>
<section id="assumptions-and-diagnostics" class="level1">
<h1>Assumptions and Diagnostics</h1>
<p>The same three assumptions from the two-sample <span class="math inline">\(t\)</span>-test apply, in the same order of importance:</p>
<ol type="1">
<li><strong>Independence</strong> of observations.</li>
<li><strong>Equal variance</strong> across all groups.</li>
<li><strong>Normality</strong> (approximately symmetric, no severe outliers).</li>
</ol>
<p><strong>New tool for checking assumptions 2 and 3: residual plots.</strong></p>
<p>The <strong>residual</strong> for observation <span class="math inline">\((i,j)\)</span> under the full model is: <span class="math display">\[e_{ij} = Y_{ij} - \bar{Y}_{i\bullet}\]</span></p>
<p>Plotting residuals removes the group-mean structure, letting us focus on the <em>variation about the mean</em> without visual clutter from the differences in means between groups.</p>
<section id="residual-plots-in-r" class="level2">
<h2 class="anchored" data-anchor-id="residual-plots-in-r">Residual Plots in R</h2>
<p>The quickest way is <code>plot()</code> applied to an <code>aov()</code> object:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(aout_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/base-resid-plots-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two most important panels:</p>
<ul>
<li><strong>Residuals vs.&nbsp;Fitted</strong>: residuals (<span class="math inline">\(y\)</span>-axis) vs.&nbsp;group means (<span class="math inline">\(x\)</span>-axis). Look for unequal spread across the fitted values.</li>
<li><strong>Normal Q-Q</strong>: QQ-plot of residuals. Look for departures from a straight line (skew, heavy tails, outliers).</li>
</ul>
</section>
<section id="manual-ggplot2-residual-plots" class="level2">
<h2 class="anchored" data-anchor-id="manual-ggplot2-residual-plots">Manual <code>ggplot2</code> Residual Plots</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>resid_vec  <span class="ot">&lt;-</span> <span class="fu">residuals</span>(aout_full)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>fitted_vec <span class="ot">&lt;-</span> <span class="fu">fitted</span>(aout_full)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>resid_df   <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">resid =</span> resid_vec, <span class="at">fitted =</span> fitted_vec,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Judge =</span> case0502<span class="sc">$</span>Judge)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>p_rv_fit <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(resid_df, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fitted values (group means)"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Residuals vs. fitted"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>p_rv_grp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(resid_df, <span class="fu">aes</span>(<span class="at">x =</span> Judge, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Residuals"</span>, <span class="at">title =</span> <span class="st">"Residuals by group"</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>p_rv_fit <span class="sc">+</span> p_rv_grp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/ggplot-resids-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resid_df, <span class="fu">aes</span>(<span class="at">sample =</span> resid)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Normal Q-Q plot of residuals"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/qq-resid-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-to-look-for" class="level2">
<h2 class="anchored" data-anchor-id="what-to-look-for">What to Look For</h2>
<p><strong>Unequal variance</strong> appears as fan-shaped spread in the Residuals vs. Fitted plot — larger spread for larger fitted values (or vice versa):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/bad-unequal-var-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p><strong>An outlier</strong> appears as an isolated point far from 0:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_ch5_files/figure-html/bad-outlier-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p><strong>Solutions</strong> mirror Chapter 3:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Violation</th>
<th style="text-align: left;">Solution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Independence</td>
<td style="text-align: left;">ANOVA with blocking (Chapters 12–13)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unequal variance</td>
<td style="text-align: left;">Welch-style ANOVA; log transformation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-normality / outliers</td>
<td style="text-align: left;">Transformation; run with and without outlier</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="random-effects" class="level1">
<h1>Random Effects</h1>
<p>In the fixed-effects model above, the groups (judges, diets) are the specific groups of interest — we want to compare these particular groups.</p>
<p>Sometimes the groups are <strong>not</strong> of direct interest. Instead, they are a random sample from a larger population of groups, and we want to make inferences about <strong>variability among groups</strong> in that population.</p>
<p><strong>Example</strong>: Quality control — measuring output of 7 randomly selected machines from a factory. We don’t care about those specific 7 machines; we want to know how much machine-to-machine variability exists across the entire factory floor.</p>
<p>When groups are a random sample from a larger population of groups, use the <strong>random-effects model</strong>.</p>
<section id="the-random-effects-model" class="level2">
<h2 class="anchored" data-anchor-id="the-random-effects-model">The Random-Effects Model</h2>
<p>The model is written in two layers:</p>
<p><span class="math display">\[Y_{ij} = \mu_i + \varepsilon_{ij},
\quad \text{var}(\varepsilon_{ij}) = \sigma^2\]</span> <span class="math display">\[\mu_i = \mu + \xi_i,
\quad \text{var}(\xi_i) = \sigma_p^2\]</span></p>
<p>The first line is identical to the fixed-effects model. The second line says that each group mean <span class="math inline">\(\mu_i\)</span> is itself <strong>random</strong> — it is the overall average <span class="math inline">\(\mu\)</span> plus a random group-specific deviation <span class="math inline">\(\xi_i\)</span>. These deviations have mean 0 and variance <span class="math inline">\(\sigma_p^2\)</span>.</p>
<p>In words: every observation has two sources of randomness:</p>
<ol type="1">
<li><strong>Within-group noise</strong> <span class="math inline">\(\varepsilon_{ij}\)</span>: how much individual <span class="math inline">\(j\)</span> in group <span class="math inline">\(i\)</span> differs from its group’s mean (variance <span class="math inline">\(\sigma^2\)</span>).</li>
<li><strong>Between-group noise</strong> <span class="math inline">\(\xi_i\)</span>: how much group <span class="math inline">\(i\)</span>’s mean differs from the overall mean <span class="math inline">\(\mu\)</span> (variance <span class="math inline">\(\sigma_p^2\)</span>).</li>
</ol>
<p>If <span class="math inline">\(\sigma_p^2 = 0\)</span>, all groups have the same true mean (<span class="math inline">\(\mu_i = \mu\)</span> for all <span class="math inline">\(i\)</span>), and there is no between-group variability at all.</p>
<p><strong>Hypotheses:</strong> <span class="math display">\[H_0: \sigma_p^2 = 0 \quad \text{(no between-group variability — all group means equal } \mu\text{)}\]</span> <span class="math display">\[H_A: \sigma_p^2 &gt; 0 \quad \text{(some groups have higher/lower means than others)}\]</span></p>
<p>We run the <strong>same <span class="math inline">\(F\)</span>-test as before</strong>. Under <span class="math inline">\(H_0\)</span>, the <span class="math inline">\(F\)</span>-statistic has the same <span class="math inline">\(F_{I-1,\, n-I}\)</span> null distribution.</p>
</section>
<section id="why-use-this-model" class="level2">
<h2 class="anchored" data-anchor-id="why-use-this-model">Why Use This Model?</h2>
<p>In one-way ANOVA, the <span class="math inline">\(p\)</span>-value from the <span class="math inline">\(F\)</span>-test is identical whether you treat groups as fixed or random. So why bother with random effects?</p>
<p>In more complex models — for example, when you have multiple random factors, or when the same individuals appear in multiple groups — treating groups as random leads to different (and generally better) estimates and inference. The one-way case is the simplest introduction to this framework.</p>
</section>
<section id="intraclass-correlation-icc" class="level2">
<h2 class="anchored" data-anchor-id="intraclass-correlation-icc">Intraclass Correlation (ICC)</h2>
<p>The ICC measures the <strong>proportion of total variance explained by group membership</strong>:</p>
<p><span class="math display">\[\text{ICC} = \frac{\hat\sigma_p^2}{\hat\sigma_p^2 + \hat\sigma^2}\]</span></p>
<p>To see why: the total variance of any observation <span class="math inline">\(Y_{ij}\)</span> is <span class="math inline">\(\sigma_p^2 + \sigma^2\)</span> (between-group plus within-group). The ICC is the fraction of that total coming from between-group differences.</p>
<ul>
<li><strong>ICC close to 1</strong>: most variation is <em>between</em> groups — knowing the group an observation belongs to tells you most of what you need to know about its value.</li>
<li><strong>ICC close to 0</strong>: most variation is <em>within</em> groups — group membership explains very little; individual-level noise dominates.</li>
</ul>
<hr>
</section>
</section>
<section id="exercises" class="level1">
<h1>Exercises</h1>
<p><strong>1.</strong> The diet study (Case Study 5.1.1) is a randomized experiment, while the Spock trial (Case Study 5.1.2) is an observational study.</p>
<ol type="a">
<li>For each study, identify the explanatory variable and the response variable.</li>
<li>For each study, state whether a causal conclusion is justified if the <span class="math inline">\(F\)</span>-test is significant. Explain.</li>
</ol>
<p><strong>2.</strong> Using the diet data (<code>case0501</code>):</p>
<ol type="a">
<li>Fit the one-way ANOVA model with <code>aov()</code> and display the ANOVA table.</li>
<li>State the null and alternative hypotheses for the omnibus <span class="math inline">\(F\)</span>-test.</li>
<li>Report the <span class="math inline">\(F\)</span>-statistic, degrees of freedom, and <span class="math inline">\(p\)</span>-value. What do you conclude?</li>
</ol>
<p><strong>3.</strong> From the ANOVA table in Exercise 2, identify (by number, not name):</p>
<ol type="a">
<li><span class="math inline">\(RSS_{full}\)</span> and <span class="math inline">\(df_{full}\)</span>.</li>
<li><span class="math inline">\(s_p^2\)</span> (the pooled variance estimate).</li>
<li><span class="math inline">\(ESS\)</span> and <span class="math inline">\(df_{extra}\)</span>.</li>
<li>The <span class="math inline">\(F\)</span>-statistic — verify it equals <span class="math inline">\(ESS/df_{extra}\)</span> divided by <span class="math inline">\(s_p^2\)</span>.</li>
</ol>
<p><strong>4.</strong> For the Spock data, use <code>pairwise.t.test()</code> to obtain all pairwise <span class="math inline">\(p\)</span>-values (unadjusted).</p>
<ol type="a">
<li>How many pairwise comparisons are there?</li>
<li>Which pairs, if any, show evidence of a difference at <span class="math inline">\(\alpha = 0.05\)</span>?</li>
<li>Why is it potentially problematic to use <span class="math inline">\(\alpha = 0.05\)</span> for each test individually when conducting this many comparisons?</li>
</ol>
<p><strong>5.</strong> Fit the three nested models for the Spock data (null, intermediate, full) and reproduce the sequential ANOVA table using <code>anova()</code>.</p>
<ol type="a">
<li>What is Spock’s judge’s estimated percent-women on the venire?</li>
<li>What is the pooled estimate for the other six judges?</li>
<li>Interpret the two <span class="math inline">\(F\)</span>-tests in the sequential table. What overall conclusion do you draw about the Spock trial jury selection?</li>
</ol>
<p><strong>6.</strong> For the diet study, test whether the two most calorie-restricted groups (N/R40 and R/R50) differ in mean lifetime from the control group (N/N85).</p>
<ol type="a">
<li>Create a new binary variable that indicates whether the mouse is in one of those two groups vs.&nbsp;the control group.</li>
<li>Fit the appropriate reduced model and use <code>anova()</code> to test the hypothesis.</li>
<li>Interpret the result.</li>
</ol>
<p><strong>7.</strong> For the Spock data, make the three residual plots:</p>
<ol type="a">
<li>Residuals vs.&nbsp;fitted values.</li>
<li>Residuals vs.&nbsp;judge (boxplots).</li>
<li>QQ-plot of residuals.</li>
</ol>
<p>Comment on whether the equal-variance and normality assumptions appear reasonable.</p>
<p><strong>8.</strong> Explain in your own words why the pooled variance estimate <span class="math inline">\(s_p^2\)</span> uses <strong>all</strong> groups (not just the two being compared) when conducting a pairwise <span class="math inline">\(t\)</span>-test in the one-way ANOVA framework. What is the practical benefit of this approach?</p>
<p><strong>9.</strong> For the Spock data, the omnibus <span class="math inline">\(F\)</span>-test gives a very small <span class="math inline">\(p\)</span>-value.</p>
<ol type="a">
<li>Does a significant omnibus <span class="math inline">\(F\)</span>-test tell you <em>which</em> pairs of means differ? Explain.</li>
<li>After seeing a significant omnibus result, a student decides to examine only the comparison that looks most different in the boxplot and ignores the others. What is the statistical problem with this strategy?</li>
</ol>
<p><strong>10.</strong> Consider a one-way ANOVA with <span class="math inline">\(I = 4\)</span> groups and <span class="math inline">\(n = 40\)</span> total observations.</p>
<ol type="a">
<li>What are <span class="math inline">\(df_{extra}\)</span> and <span class="math inline">\(df_{full}\)</span>?</li>
<li>If <span class="math inline">\(RSS_{full} = 720\)</span> and <span class="math inline">\(ESS = 180\)</span>, compute <span class="math inline">\(s_p^2\)</span>, the <span class="math inline">\(F\)</span>-statistic, and the <span class="math inline">\(p\)</span>-value.</li>
<li>What is the <span class="math inline">\(p\)</span>-value from <code>pf()</code> in R?</li>
</ol>
<p><strong>11.</strong> Describe the difference between a <strong>fixed-effects</strong> and a <strong>random-effects</strong> one-way ANOVA model. For each scenario below, state which model is more appropriate and why.</p>
<ol type="a">
<li>Comparing mean test scores across 5 specific schools that were chosen because they use different curricula.</li>
<li>Comparing output quality across 6 machines randomly selected from a factory floor, to estimate how much machine-to-machine variability exists.</li>
<li>Comparing soil nitrogen levels across 8 randomly chosen plots in a large field.</li>
</ol>
<p><strong>12.</strong> A researcher fits a one-way ANOVA with <span class="math inline">\(I = 5\)</span> groups and finds <span class="math inline">\(RSS_{full} = 400\)</span> (df = 45), <span class="math inline">\(RSS_{reduced} = 520\)</span> (df = 49).</p>
<ol type="a">
<li>Compute <span class="math inline">\(ESS\)</span> and <span class="math inline">\(df_{extra}\)</span>.</li>
<li>Compute <span class="math inline">\(s_p^2\)</span> and the <span class="math inline">\(F\)</span>-statistic.</li>
<li>Compute the <span class="math inline">\(p\)</span>-value. Is there evidence of group differences?</li>
<li>Compute the ICC estimate, given that the estimated between-group variance is <span class="math inline">\(\hat\sigma_p^2 = 6.0\)</span>.</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>