project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "**/*.qmd"

website:
  title: "Stat 302: Intermediate Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data.qmd

execute:
  dir: file

format:
  html:
    theme: [flatly, theme.scss]
    css: styles.css
    toc: true
    axe: true
    highlight-style: a11y
