---
title: "STAT-302 Homepage"
author: David Gerard
---

[Syllabus](./syllabus.qmd)

- Final project
  - [Final Project Description](./project/group_project.qmd)
  - [Three Stories of Regression](./project/regression_stories.qmd)
  - [AU Data Subscriptions](https://subjectguides.library.american.edu/az/databases?t=7411)
  - [AU Data Librarian Resources](https://subjectguides.library.american.edu/c.php?g=1329947&p=9793262)
  - [AU List of Government Data](https://subjectguides.library.american.edu/c.php?g=1329947&p=9988298)
- Chapter 0: R
  - [R and Data Frames](./01_r/01_r_intro.qmd)
  - [R Graphics](./01_r/01_ggplot.qmd)
  - [R Cheat Sheet](./01_r/01_r_cheatsheet.qmd)
- Review:
  - [Basic Statistics Review](./02_review/02_stat_202_review.qmd)
  - [Probability Review](./02_review/02_prob_review.qmd)
- Chapter 1:
  - [Causality and Generalizability](./03_ch1/03_ch1.qmd)
  - [Chapter 1 Worksheet](./03_ch1/03_worksheet.qmd)
- Chapter 2:
  - [Paired and Two-Sample t-Tests](./04_ch2/04_ch2.qmd)
  - [Chapter 2 Worksheet](./04_ch2/04_worksheet.qmd)
- Chapter 3:
  - [Assumptions of t-Tools](./05_ch3/05_ch3.qmd)
  - [Review: Logarithms and Exponentials](./05_ch3/05_log_review.qmd)
  - [Chapter 3 Worksheet](./05_ch3/05_worksheet.qmd)
- Chapter 4:
  - Nonparameterics
- Chapter 5:
  - [One-Way ANOVA](./07_ch5/07_ch5.qmd)
  - [Chapter 5 Worksheet](./07_ch5/07_worksheet.qmd)
- Chapter 6:
  - [Linear Combinations of Group Means](./08_ch6/08_linear_combos.qmd)
  - [Multiple Comparisons](./08_ch6/08_multiple_comparisons.qmd)
  - [Chapter 6 Worksheet](./08_ch6/08_worksheet.qmd)
- Chapter 7:
  - [Simple Linear Regression](./09_ch7/09_ch7.qmd)
  - [Chapter 7 Worksheet](./09_ch7/09_worksheet.qmd)
- Chapter 8:
  - [Assumptions of Simple Linear Regression](./10_ch8/10_ch8.qmd)
  - [Chapter 8 Worksheet](./10_ch8/10_worksheet.qmd)
- Chapters 9
  - [Multiple Linear Regression](./11_ch9/11_multiple_regression.qmd)
  - [Transformations](./11_ch9/11_limitless_possibilities.qmd)
  - [MLR EDA](./11_ch9/11_multiple_regression_eda.qmd)
- Chapters 10–12:
  - [F-tests for Nested Models](./12_modeling/12_f_tests.qmd)
  - [Model Selection](./12_modeling/12_model_selection.qmd)
  - [Outliers and Influential Observations](./12_modeling/12_outliers.qmd)
  - [Chapters 10–12 Worksheet](./12_modeling/12_worksheet.qmd)
- Chapter 13:
  - [Why Use Two-Way ANOVA?](./13_ch13/13_why_two_way.qmd)
  - [Two-Way ANOVA](./13_ch13/13_two_way_anova.qmd)
  - [Multi-Factor ANOVA](./13_ch13/13_multifactor.qmd)
  - [Chapter 13 Worksheet](./13_ch13/13_worksheet.qmd)
- Chapter 20:
  - [Logistic Regression](./14_ch20/14_logistic.qmd)
